### ISSUE TITLE
I keep getting an odd error in my django app

### ISSUE THREAD

**Issue by idesignedme** [django/django-contrib-comments#98]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10413e268>
Traceback (most recent call last):
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
(practice) apples-MacBook-Pro:src ray$ ./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x104060488>
Traceback (most recent call last):
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ray/Desktop/myheroku/practice/src/blog/models.py", line 11, in <module>
    from dynamic_scraper.models import Scraper, SchedulerRuntime
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/dynamic_scraper/models.py", line 13, in <module>
    class ScrapedObjClass(models.Model):
  File "/Users/ray/Desktop/myheroku/practice/lib/python3.5/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class dynamic_scraper.models.ScrapedObjClass doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

whhen I try to use django dynamic scraper

**Comment by claudep** [comment]
Sorry, but I don't see anything related with django-contrib-comments here.
